groups:
  aruba:
    platform: aruba_aoscx
    username: admin
    password: aruba@123

    hosts:
      cx-01:
        host: 192.168.211.130

      cx-02:
        host: 192.168.211.131

  linux:
    platform: linux
    username: aruba
    password: Aruba@123

    hosts:
      ubuntu:
        host: 192.168.211.136
